### PR TITLE
Remove total count from the pagination component

### PR DESCRIPTION
**Pull request by juliangiebel**

### CODE REVIEW

**Review by PJB3005 — CHANGES_REQUESTED** [review]
The total count is still really useful to have and it isn't a problem on any table except the admin logs right now. Don't blanket remove the whole thing.

**Comment by juliangiebel** [comment]
Well change it to use the estimate then as the other tables will just get slower and slower with the `SELECT COUNT(*)` query.

**Comment by PJB3005** [comment]
I checked it against the largest table we have (connections) and it's still fine.

**Comment by juliangiebel** [comment]
I'm opening a different PR where I use the count estimate for the admin logs table

**Pull request closed without merging**
