### PR TITLE
ISO 8601 dates

### LINKED ISSUE #16: ISO 8601 (YYYY-MM-DD) should be used over other formats
I propose we don't use it and instead use [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) (YYYY-MM-DD). Using this will reduce ambiguity and confusion for many admins.

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
Closes #16

Changes the format date to be "YYYY/MM/DD HH:MM:SS"

Hopefully "g" is nothing important... right?

image
image
image

### CODE REVIEW

**Comment by 0x6273** [comment]
ISO8601 uses `-` not `/`

**Comment by VasilisThePikachu** [comment]
> ISO8601 uses `-` not `/`

Is it really that important?

**Comment by VasilisThePikachu** [comment]
Highly doupt adding some dashes will make it any less hard to understand

**Comment by VasilisThePikachu** [comment]
FUCK

**Review by juliangiebel — COMMENTED** [review]
Vasilis webdev 10/10
Lgtm!

**Review by juliangiebel — APPROVED** [review]
Forgor to approve

**Pull request merged**
